"""C backend: emit self-contained, table-driven C kernels (plan phase 3).

Design: the largest kernels have >100k scalar monomials per coefficient sum;
emitting them as inline expressions would defeat any compiler, and full CSE is
future work.  Instead each kernel is emitted as **static tables + a small
fixed evaluator**:

  * a flat monomial table per pattern: coefficients, factor-list offsets, and
    factor ids indexing an ordered list of per-point scalar arrays
    (powers > 1 encoded by factor repetition);
  * stage A: one loop over grid points walking the table -> coefficient c(g);
  * stage B: plain triple loop  out[u,v] += U[u,g] * c[g] * V[v,g]
    (BLAS/Einsums variants are drop-in replacements later; the evaluator body
    is deliberately `restrict`-annotated plain C99 so it can also be wrapped
    as a __host__ __device__ function for the device backends).

ABI (v1, one perturbation-batch entry per call; hosts loop the batch):

  int <name>(int64_t npts, int64_t nbf,
             const double* chi,        /* nbf x npts, row-major */
             const double* dchi,       /* 3 x nbf x npts */
             const double* lapl_chi,   /* nbf x npts, may be NULL if unused */
             const double* const* scal,/* n_scal arrays (npts,) -- see the
                                          generated <name>_scal_names table */
             double* out);             /* nbf x nbf, accumulated (+=) */

The scalar-operand order is emitted both as a C string table and returned by
scal_order() for programmatic assembly (the ctypes validation uses it).
"""

from __future__ import annotations

import re
from typing import List, Tuple

from .codegen import CollapsedKernel, _classify

#: basis-factor code -> (array expression, needs)
_BASIS = {
    "chi": ("chi", None),
    "dchi[0]": ("dchi + (size_t)0*nbf*npts", None),
    "dchi[1]": ("dchi + (size_t)1*nbf*npts", None),
    "dchi[2]": ("dchi + (size_t)2*nbf*npts", None),
    "lapl_chi": ("lapl_chi", "lapl"),
}


def scal_order(ck: CollapsedKernel) -> List[str]:
    """Ordered scalar-operand names for the `scal` pointer array.

    Vector parameters are flattened to components (grad_rho -> grad_rho_x..z),
    matching the manifest parameter order.
    """
    order: List[str] = []
    for p in ck.params:
        if p in ("chi", "dchi", "lapl_chi"):
            continue
        if p.startswith("grad_rho"):
            for ax in ("x", "y", "z"):
                # grad_rho -> grad_rho_x; grad_rho_a_p1 -> grad_rho_a_p1_x
                order.append(f"{p}_{ax}")
        else:
            order.append(p)
    return order


def _scal_index(ck: CollapsedKernel) -> dict:
    return {name: i for i, name in enumerate(scal_order(ck))}


def emit_c(ck: CollapsedKernel, name: str) -> str:
    """Emit a self-contained C99 translation unit for one kernel."""
    sidx = _scal_index(ck)
    lines: List[str] = [
        "/* generated by xckernel (table-driven pattern-collapsed kernel) */",
        "#include <stdint.h>",
        "#include <stdlib.h>",
        "",
        f"/* scalar operand order for the `scal` argument: */",
    ]
    names = scal_order(ck)
    lines.append(f"const char* {name}_scal_names[{len(names)}] = {{")
    for n in names:
        lines.append(f'    "{n}",')
    lines += ["};", f"const int {name}_n_scal = {len(names)};", ""]

    # monomial tables per pattern
    pat_meta = []
    for ip, (ufac, vfac, monos) in enumerate(ck.patterns):
        coeffs, offs, fids = [], [0], []
        for coeff, factors in monos:
            coeffs.append(coeff)
            for fname, e in factors:
                fids.extend([sidx[fname]] * e)
            offs.append(len(fids))
        lines.append(f"static const double {name}_c{ip}[] = {{")
        lines.append("    " + ",".join(f"{c!r}" for c in coeffs))
        lines.append("};")
        lines.append(f"static const int32_t {name}_o{ip}[] = {{")
        lines.append("    " + ",".join(str(o) for o in offs))
        lines.append("};")
        lines.append(f"static const uint16_t {name}_f{ip}[] = {{")
        lines.append("    " + (",".join(str(f) for f in fids) or "0"))
        lines.append("};")
        pat_meta.append((ip, ufac, vfac, len(monos)))
    lines.append("")

    # the fixed evaluator (stage A) + distributor (stage B)
    lines += [
        "static void stage_a(int64_t npts, int64_t nm,",
        "                    const double* restrict cf,",
        "                    const int32_t* restrict off,",
        "                    const uint16_t* restrict fid,",
        "                    const double* const* restrict scal,",
        "                    double* restrict c) {",
        "    for (int64_t g = 0; g < npts; ++g) {",
        "        double acc = 0.0;",
        "        for (int64_t m = 0; m < nm; ++m) {",
        "            double t = cf[m];",
        "            for (int32_t f = off[m]; f < off[m+1]; ++f)",
        "                t *= scal[fid[f]][g];",
        "            acc += t;",
        "        }",
        "        c[g] = acc;",
        "    }",
        "}",
        "",
        "static void stage_b(int64_t npts, int64_t nbf,",
        "                    const double* restrict U,",
        "                    const double* restrict c,",
        "                    const double* restrict V,",
        "                    double* restrict out) {",
        "    for (int64_t u = 0; u < nbf; ++u) {",
        "        for (int64_t v = 0; v < nbf; ++v) {",
        "            double s = 0.0;",
        "            const double* Ug = U + u*npts;",
        "            const double* Vg = V + v*npts;",
        "            for (int64_t g = 0; g < npts; ++g)",
        "                s += Ug[g] * c[g] * Vg[g];",
        "            out[u*nbf + v] += s;",
        "        }",
        "    }",
        "}",
        "",
        f"int {name}(int64_t npts, int64_t nbf,",
        "           const double* chi, const double* dchi,",
        "           const double* lapl_chi,",
        "           const double* const* scal, double* out) {",
        "    double* c = (double*)malloc((size_t)npts * sizeof(double));",
        "    if (!c) return 1;",
    ]
    for ip, ufac, vfac, nm in pat_meta:
        uexpr = _BASIS[ufac][0]
        vexpr = _BASIS[vfac][0]
        lines += [
            f"    stage_a(npts, {nm}, {name}_c{ip}, {name}_o{ip}, "
            f"{name}_f{ip}, scal, c);",
            f"    stage_b(npts, nbf, {uexpr}, c, {vexpr}, out);",
        ]
    lines += ["    free(c);", "    return 0;", "}", ""]
    return "\n".join(lines)


# --- package emission (libxckernel) ------------------------------------------

_KERNEL_PROTO = ("int {name}(int64_t npts, int64_t nbf,\n"
                 "           const double* chi, const double* dchi,\n"
                 "           const double* lapl_chi,\n"
                 "           const double* const* scal, double* out);")


def emit_header(kernel_names: List[str], version: str) -> str:
    """The public C header for libxckernel."""
    lines = [
        "/* libxckernel: generated exchange-correlation kernel contractions",
        " * (an automatic-differentiation backend for Libxc).",
        f" * Version {version}. Generated by xckernel; do not edit.",
        " *",
        " * ABI: one perturbation-batch entry per call; `scal` is an ordered",
        " * array of per-point scalar operands (see <name>_scal_names /",
        " * manifest.json); `out` is accumulated (+=). Returns 0 on success.",
        " * Kernels contain XC terms only: Coulomb, HF and range-separated",
        " * exchange are host-owned.",
        " */",
        "#ifndef XCKERNEL_H",
        "#define XCKERNEL_H",
        "#include <stdint.h>",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f'#define XCKERNEL_VERSION "{version}"',
        "",
    ]
    for name in kernel_names:
        lines.append(_KERNEL_PROTO.format(name=name))
        lines.append(f"extern const char* {name}_scal_names[];")
        lines.append(f"extern const int {name}_n_scal;")
        lines.append("")
    lines += ["#ifdef __cplusplus", "}", "#endif", "#endif /* XCKERNEL_H */",
              ""]
    return "\n".join(lines)


def emit_f03(kernel_names: List[str], version: str) -> str:
    """The Fortran 2003 ISO_C_BINDING module (the xc_f03 idiom)."""
    lines = [
        "! libxckernel Fortran interface. Generated by xckernel; do not edit.",
        f"! Version {version}.",
        "! Scalar operands are passed as an array of C pointers in the order",
        "! given by the kernel's manifest entry (see manifest.json).",
        "module xckernel_f03",
        "  use, intrinsic :: iso_c_binding, only: c_int, c_int64_t, "
        "c_double, c_ptr",
        "  implicit none",
        "  public",
        "  interface",
    ]
    for name in kernel_names:
        lines += [
            f"    integer(c_int) function {name}(npts, nbf, chi, dchi, "
            f"lapl_chi, scal, out) bind(C, name='{name}')",
            "      import :: c_int, c_int64_t, c_double, c_ptr",
            "      integer(c_int64_t), value :: npts, nbf",
            "      real(c_double), intent(in) :: chi(*), dchi(*)",
            "      type(c_ptr), value :: lapl_chi",
            "      type(c_ptr), intent(in) :: scal(*)",
            "      real(c_double), intent(inout) :: out(*)",
            f"    end function {name}",
        ]
    lines += ["  end interface", "end module xckernel_f03", ""]
    return "\n".join(lines)


def emit_cmake(kernel_names: List[str], version: str) -> str:
    srcs = "\n    ".join(f"src/{n}.c" for n in kernel_names)
    return f"""\
# libxckernel build. Generated by xckernel; do not edit.
cmake_minimum_required(VERSION 3.16)
project(xckernel VERSION {version} LANGUAGES C)

option(XCKERNEL_FORTRAN "Build the Fortran interface module" ON)

add_library(xckernel
    {srcs}
)
set_target_properties(xckernel PROPERTIES
    C_STANDARD 99
    POSITION_INDEPENDENT_CODE ON
    VERSION ${{PROJECT_VERSION}}
    SOVERSION ${{PROJECT_VERSION_MAJOR}})
target_include_directories(xckernel PUBLIC
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_SOURCE_DIR}}/include>
    $<INSTALL_INTERFACE:include>)

if(XCKERNEL_FORTRAN)
    enable_language(Fortran)
    add_library(xckernel_f03 fortran/xckernel_f03.f90)
    target_link_libraries(xckernel_f03 PUBLIC xckernel)
endif()

include(GNUInstallDirs)
install(TARGETS xckernel EXPORT xckernelTargets
    LIBRARY DESTINATION ${{CMAKE_INSTALL_LIBDIR}}
    ARCHIVE DESTINATION ${{CMAKE_INSTALL_LIBDIR}})
install(FILES include/xckernel.h DESTINATION ${{CMAKE_INSTALL_INCLUDEDIR}})
install(FILES manifest.json
    DESTINATION ${{CMAKE_INSTALL_DATADIR}}/xckernel)
if(XCKERNEL_FORTRAN)
    install(TARGETS xckernel_f03 EXPORT xckernelTargets
        LIBRARY DESTINATION ${{CMAKE_INSTALL_LIBDIR}}
        ARCHIVE DESTINATION ${{CMAKE_INSTALL_LIBDIR}})
endif()
install(EXPORT xckernelTargets NAMESPACE xckernel::
    DESTINATION ${{CMAKE_INSTALL_LIBDIR}}/cmake/xckernel)
"""
