"""End-to-end demo: generated einsum code vs PySCF's own XC matrices.

For a real molecule on a real DFT grid we

  1. get AO values + derivatives and the density on the grid from PySCF,
  2. get the Libxc derivatives (vrho, vsigma, ..., v2rho2, ...) from PySCF,
  3. feed those into the einsum function generated by xckernel.codegen,
  4. compare against PySCF's own numint.nr_rks (XC Fock) and nr_rks_fxc
     (the fxc kernel contracted with a trial density -- the orbital Hessian core).

Agreement to ~1e-10 shows the generated "AD backend for Libxc" reproduces a
production DFT code's exchange-correlation build.
"""

from __future__ import annotations

import numpy as np
from pyscf import gto, dft
from pyscf.dft import numint

from ..engine.kernel import fock, xc_kernel
from ..emitters.codegen import generate, compile_function

XCTYPE = {"lda": "LDA", "gga": "GGA"}
XC = {"lda": "LDA_X,", "gga": "PBE"}   # ',' => exchange-only LDA (no correlation)


def _operands(ao, rho, xctype):
    """Common operands for the generated function from PySCF grid data."""
    if xctype == "LDA":
        chi = ao.T                              # (nao, ng)   ao is (ng, nao)
        dchi = np.zeros((3,) + chi.shape)
        grad_rho = None
    else:
        chi = ao[0].T
        dchi = np.transpose(ao[1:4], (0, 2, 1))  # (3, nao, ng)
        grad_rho = rho[1:4]                       # (3, ng)
    return chi, dchi, grad_rho


def demo_fock(family, mol, grids, dm):
    xc, xctype = XC[family], XCTYPE[family]
    ni = numint.NumInt()

    deriv = 0 if xctype == "LDA" else 1
    ao = numint.eval_ao(mol, grids.coords, deriv=deriv)
    rho = numint.eval_rho(mol, ao, dm, xctype=xctype)

    # plain eval_xc first-derivative outputs keep names 1:1 with our symbols.
    _, vxc2 = dft.libxc.eval_xc(xc, rho, spin=0, deriv=1)[:2]
    vrho = vxc2[0]
    w = grids.weights

    fn = compile_function(generate(fock(family), "fock_fn"))
    chi, dchi, grad_rho = _operands(ao, rho, xctype)

    if xctype == "LDA":
        F = fn(w, chi, dchi, vrho)
    else:
        vsigma = vxc2[1]
        F = fn(w, chi, dchi, grad_rho, vrho, vsigma)

    _, _, vref = ni.nr_rks(mol, grids, xc, dm)
    err = np.max(np.abs(F - vref))
    return err, np.max(np.abs(vref))


def demo_fxc(family, mol, grids, dm, dm1):
    xc, xctype = XC[family], XCTYPE[family]
    ni = numint.NumInt()

    deriv = 0 if xctype == "LDA" else 1
    ao = numint.eval_ao(mol, grids.coords, deriv=deriv)
    rho = numint.eval_rho(mol, ao, dm, xctype=xctype)
    _, vxc2, fxc2 = dft.libxc.eval_xc(xc, rho, spin=0, deriv=2)[:3]
    w = grids.weights
    chi, dchi, grad_rho = _operands(ao, rho, xctype)

    gen = generate(xc_kernel(family), "kernel_fn")
    fn = compile_function(gen)

    libxc = {"vrho": vxc2[0], "v2rho2": fxc2[0]}
    if xctype != "LDA":
        libxc.update(vsigma=vxc2[1], v2rhosigma=fxc2[1], v2sigma2=fxc2[2])

    args = [w, chi, dchi]
    if gen.uses_grad_rho:
        args.append(grad_rho)
    args += [libxc[name] for name in gen.libxc_args]
    G = fn(*args)                                   # (nao, nao, nao, nao)

    # response of the XC potential to a density change dm1:  R_uv = g_uv,ts dm1_ts
    R = np.einsum("uvts,ts->uv", G, dm1)

    # let PySCF compute rho0/vxc/fxc internally (its packed ndarray format)
    Rref = ni.nr_rks_fxc(mol, grids, xc, dm, dm1, hermi=0)
    err = np.max(np.abs(R - Rref))
    return err, np.max(np.abs(Rref))


def main():
    mol = gto.M(atom="O 0 0 0; H 0 0 0.96; H 0 0.93 -0.24", basis="sto-3g",
                verbose=0)
    grids = dft.gen_grid.Grids(mol)
    grids.level = 3
    grids.build()

    # a physical density matrix from a cheap converged LDA calculation
    mf = dft.RKS(mol); mf.xc = "LDA,VWN"; mf.verbose = 0; mf.kernel()
    dm = mf.make_rdm1()
    rng = np.random.default_rng(0)
    a = rng.standard_normal(dm.shape)
    dm1 = a + a.T                     # symmetric trial density perturbation

    print(f"molecule: H2O/sto-3g, nao={mol.nao}, ngrid={len(grids.weights)}\n")
    print("XC Fock  F_uv vs PySCF numint.nr_rks")
    for fam in ("lda", "gga"):
        err, scale = demo_fock(fam, mol, grids, dm)
        ok = "OK " if err / (scale or 1) < 1e-9 else "FAIL"
        print(f"  [{ok}] {fam:4s} max_abs_err={err:.3e}  rel={err/(scale or 1):.3e}")

    print("\nfxc response  (g_uv,ts dm1_ts) vs PySCF numint.nr_rks_fxc")
    for fam in ("lda", "gga"):
        err, scale = demo_fxc(fam, mol, grids, dm, dm1)
        ok = "OK " if err / (scale or 1) < 1e-9 else "FAIL"
        print(f"  [{ok}] {fam:4s} max_abs_err={err:.3e}  rel={err/(scale or 1):.3e}")


if __name__ == "__main__":
    main()
