"""C backend: emit self-contained, table-driven C kernels (plan phase 3).

Design: the largest kernels have >100k scalar monomials per coefficient sum;
emitting them as inline expressions would defeat any compiler, and full CSE is
future work.  Instead each kernel is emitted as **static tables + a small
fixed evaluator**:

  * a flat monomial table per pattern: coefficients, factor-list offsets, and
    factor ids indexing an ordered list of per-point scalar arrays
    (powers > 1 encoded by factor repetition);
  * stage A: one loop over grid points walking the table -> coefficient c(g);
  * stage B: plain triple loop  out[u,v] += U[u,g] * c[g] * V[v,g]
    (BLAS/Einsums variants are drop-in replacements later; the evaluator body
    is deliberately `restrict`-annotated plain C99 so it can also be wrapped
    as a __host__ __device__ function for the device backends).

ABI (v1, one perturbation-batch entry per call; hosts loop the batch):

  int <name>(int64_t npts, int64_t nbf,
             const double* chi,        /* nbf x npts, row-major */
             const double* dchi,       /* 3 x nbf x npts */
             const double* lapl_chi,   /* nbf x npts, may be NULL if unused */
             const double* const* scal,/* n_scal arrays (npts,) -- see the
                                          generated <name>_scal_names table */
             double* out);             /* nbf x nbf, accumulated (+=) */

The scalar-operand order is emitted both as a C string table and returned by
scal_order() for programmatic assembly (the ctypes validation uses it).
"""

from __future__ import annotations

import re
from typing import List, Tuple

from .codegen import CollapsedKernel, _classify

#: basis-factor code -> (array expression, needs)
_BASIS = {
    "chi": ("chi", None),
    "dchi[0]": ("dchi + (int64_t)0*nbf*npts", None),
    "dchi[1]": ("dchi + (int64_t)1*nbf*npts", None),
    "dchi[2]": ("dchi + (int64_t)2*nbf*npts", None),
    "lapl_chi": ("lapl_chi", "lapl"),
    **{f"hess_chi[{k}]": (f"hess_chi + (int64_t){k}*nbf*npts", "hess")
       for k in range(6)},
}

#: packed symmetric-tensor components (density Hessian), canonical order.
_H6_COMPS = ("xx", "xy", "xz", "yy", "yz", "zz")


def scal_order(ck: CollapsedKernel) -> List[str]:
    """Ordered scalar-operand names for the `scal` pointer array.

    Vector parameters are flattened to components (grad_rho -> grad_rho_x..z),
    matching the manifest parameter order.
    """
    order: List[str] = []
    for p in ck.params:
        if p in ("chi", "dchi", "lapl_chi", "hess_chi"):
            continue
        if p.startswith("hess_rho"):
            # packed symmetric tensor: six components
            for comp in _H6_COMPS:
                order.append(f"{p}_{comp}")
        elif p.startswith(("grad_rho", "jp")):
            for ax in ("x", "y", "z"):
                # grad_rho -> grad_rho_x; grad_rho_a_p1 -> grad_rho_a_p1_x
                order.append(f"{p}_{ax}")
        else:
            order.append(p)
    return order


def _scal_index(ck: CollapsedKernel) -> dict:
    return {name: i for i, name in enumerate(scal_order(ck))}


def emit_c(ck: CollapsedKernel, name: str) -> str:
    """Emit a self-contained C99 translation unit for one kernel."""
    sidx = _scal_index(ck)
    lines: List[str] = [
        "/* machine-generated by xckernel (table-driven pattern-collapsed kernel); do not edit. Copyright (c) 2026 Susi Lehtola. */",
        "#include <stdint.h>",
        "#include <stdlib.h>",
        "",
        f"/* scalar operand order for the `scal` argument: */",
    ]
    names = scal_order(ck)
    lines.append(f"const char* {name}_scal_names[{len(names)}] = {{")
    for n in names:
        lines.append(f'    "{n}",')
    lines += ["};", f"const int {name}_n_scal = {len(names)};", ""]

    # monomial tables per pattern
    pat_meta = []
    for ip, (ufac, vfac, monos) in enumerate(ck.patterns):
        coeffs, offs, fids = [], [0], []
        for coeff, factors in monos:
            coeffs.append(coeff)
            for fname, e in factors:
                fids.extend([sidx[fname]] * e)
            offs.append(len(fids))
        lines.append(f"static const double {name}_c{ip}[] = {{")
        lines.append("    " + ",".join(f"{c!r}" for c in coeffs))
        lines.append("};")
        lines.append(f"static const int32_t {name}_o{ip}[] = {{")
        lines.append("    " + ",".join(str(o) for o in offs))
        lines.append("};")
        lines.append(f"static const uint16_t {name}_f{ip}[] = {{")
        lines.append("    " + (",".join(str(f) for f in fids) or "0"))
        lines.append("};")
        pat_meta.append((ip, ufac, vfac, len(monos)))
    lines.append("")

    # the fixed evaluator (stage A) + distributor (stage B)
    lines += [
        "static void stage_a(int64_t npts, int64_t nm,",
        "                    const double* restrict cf,",
        "                    const int32_t* restrict off,",
        "                    const uint16_t* restrict fid,",
        "                    const double* const* restrict scal,",
        "                    double* restrict c) {",
        "    for (int64_t g = 0; g < npts; ++g) {",
        "        double acc = 0.0;",
        "        for (int64_t m = 0; m < nm; ++m) {",
        "            double t = cf[m];",
        "            for (int32_t f = off[m]; f < off[m+1]; ++f)",
        "                t *= scal[fid[f]][g];",
        "            acc += t;",
        "        }",
        "        c[g] = acc;",
        "    }",
        "}",
        "",
        "static void stage_b(int64_t npts, int64_t nbf,",
        "                    const double* restrict U,",
        "                    const double* restrict c,",
        "                    const double* restrict V,",
        "                    double* restrict out) {",
        "    for (int64_t u = 0; u < nbf; ++u) {",
        "        for (int64_t v = 0; v < nbf; ++v) {",
        "            double s = 0.0;",
        "            const double* Ug = U + u*npts;",
        "            const double* Vg = V + v*npts;",
        "            for (int64_t g = 0; g < npts; ++g)",
        "                s += Ug[g] * c[g] * Vg[g];",
        "            out[u*nbf + v] += s;",
        "        }",
        "    }",
        "}",
        "",
        f"int {name}(int64_t npts, int64_t nbf,",
        "           const double* chi, const double* dchi,",
        "           const double* lapl_chi, const double* hess_chi,",
        "           const double* const* scal, double* out) {",
        "    double* c = (double*)malloc((size_t)npts * sizeof(double));",
        "    if (!c) return 1;",
    ]
    for ip, ufac, vfac, nm in pat_meta:
        uexpr = _BASIS[ufac][0]
        vexpr = _BASIS[vfac][0]
        lines += [
            f"    stage_a(npts, {nm}, {name}_c{ip}, {name}_o{ip}, "
            f"{name}_f{ip}, scal, c);",
            f"    stage_b(npts, nbf, {uexpr}, c, {vexpr}, out);",
        ]
    lines += ["    free(c);", "    return 0;", "}", ""]
    return "\n".join(lines)


# --- C++17 templated emission (the architecture of record) ------------------

_EVALUATOR_HPP = """\
/* libxckernel shared evaluator. Machine-generated by xckernel; do not
 * edit. Copyright (c) 2026 Susi Lehtola. */
#pragma once
#include <cstdint>

#if defined(__CUDACC__) || defined(__HIPCC__)
#define XCK_HD __host__ __device__
#else
#define XCK_HD
#endif

namespace xckernel {

/* Stage A: walk a monomial table, producing the per-point coefficient.
 * Templated on the floating-point type T: instantiate with float, double,
 * long double, __float128, or any type with T*T and T+T. Table
 * coefficients are dyadic rationals, exactly representable in binary
 * floating point at any precision. */
/* Operands split by provenance: `fields` (grid weights and density
 * fields, host-computed, type T) and `xc` (functional-derivative arrays,
 * type Txc -- Libxc computes in double even when the host works at higher
 * precision; Txc -> T conversion happens per access, exact when widening).
 * Factor ids < nfld index `fields`; the rest index `xc`. */
template <typename T, typename Txc = T>
XCK_HD inline void stage_a(int64_t npts, int64_t nm,
                           const double* cf, const int32_t* off,
                           const uint16_t* fid, int64_t nfld,
                           const T* const* fields, const Txc* const* xc,
                           T* c) {
    for (int64_t g = 0; g < npts; ++g) {
        T acc = T(0);
        for (int64_t m = 0; m < nm; ++m) {
            T t = T(cf[m]);
            for (int32_t f = off[m]; f < off[m + 1]; ++f) {
                const uint16_t id = fid[f];
                t *= (id < nfld) ? fields[id][g] : T(xc[id - nfld][g]);
            }
            acc += t;
        }
        c[g] = acc;
    }
}

/* Stage B: out(u,v) += sum_g U(u,g) c(g) V(v,g). The generic loops work at
 * any precision; a BLAS specialization for T=double may substitute a GEMM. */
template <typename T>
XCK_HD inline void stage_b(int64_t npts, int64_t nbf,
                           const T* U, const T* c, const T* V, T* out) {
    for (int64_t u = 0; u < nbf; ++u) {
        for (int64_t v = 0; v < nbf; ++v) {
            T s = T(0);
            const T* Ug = U + u * npts;
            const T* Vg = V + v * npts;
            for (int64_t g = 0; g < npts; ++g) s += Ug[g] * c[g] * Vg[g];
            out[u * nbf + v] += s;
        }
    }
}

} // namespace xckernel
"""


def emit_kernel_hpp(ck: CollapsedKernel, name: str) -> str:
    """Header-only templated kernel (tables + template entry point)."""
    sidx = _scal_index(ck)
    ns = f"detail_{name}"
    lines = [
        "/* generated by xckernel; do not edit. */",
        "#pragma once",
        "#include <cstdint>",
        '#include "xckernel/evaluator.hpp"',
        "",
        "namespace xckernel {",
        f"namespace {ns} {{",
    ]
    pat_meta = []
    for ip, (ufac, vfac, monos) in enumerate(ck.patterns):
        coeffs, offs, fids = [], [0], []
        for coeff, factors in monos:
            coeffs.append(coeff)
            for fname, e in factors:
                fids.extend([sidx[fname]] * e)
            offs.append(len(fids))
        lines.append(f"static constexpr double c{ip}[] = {{")
        lines.append("    " + ",".join(f"{c!r}" for c in coeffs))
        lines.append("};")
        lines.append(f"static constexpr int32_t o{ip}[] = {{")
        lines.append("    " + ",".join(str(o) for o in offs))
        lines.append("};")
        lines.append(f"static constexpr uint16_t f{ip}[] = {{")
        lines.append("    " + (",".join(str(f) for f in fids) or "0"))
        lines.append("};")
        pat_meta.append((ip, ufac, vfac, len(monos)))
    lines.append(f"static constexpr int64_t NFLD = "
                 f"{len(scal_order(ck)) - len(ck.libxc_args)};")
    lines += [f"}} // namespace {ns}", ""]

    nfld = len(scal_order(ck)) - len(ck.libxc_args)
    lines += [
        "/* fields: host-computed per-point operands (type T); xc: the",
        " * functional-derivative arrays (type Txc; Libxc computes in double",
        " * regardless of T). work: caller scratch of npts elements or",
        " * nullptr (heap-allocated internally; pass a buffer in device",
        " * code). */",
        "template <typename T, typename Txc = T>",
        f"int {name}_t(int64_t npts, int64_t nbf,",
        "             const T* chi, const T* dchi, const T* lapl_chi,",
        "             const T* hess_chi,",
        "             const T* const* fields, const Txc* const* xc,",
        "             T* out, T* work = nullptr) {",
        "    T* c = work;",
        "    bool own = false;",
        "    if (!c) { c = new (std::nothrow) T[npts]; own = true; }",
        "    if (!c) return 1;",
    ]
    _bexpr = {"chi": "chi", "lapl_chi": "lapl_chi",
              "dchi[0]": "dchi + (int64_t)0*nbf*npts",
              "dchi[1]": "dchi + (int64_t)1*nbf*npts",
              "dchi[2]": "dchi + (int64_t)2*nbf*npts",
              **{f"hess_chi[{k}]": f"hess_chi + (int64_t){k}*nbf*npts"
                 for k in range(6)}}
    for ip, ufac, vfac, nm in pat_meta:
        uexpr = _bexpr[ufac]
        vexpr = _bexpr[vfac]
        lines += [
            f"    stage_a<T, Txc>(npts, {nm}, {ns}::c{ip}, {ns}::o{ip}, "
            f"{ns}::f{ip}, {ns}::NFLD, fields, xc, c);",
            f"    stage_b<T>(npts, nbf, {uexpr}, c, {vexpr}, out);",
        ]
    lines += ["    if (own) delete[] c;", "    return 0;", "}",
              "", "} // namespace xckernel", ""]
    # <new> for std::nothrow
    lines.insert(3, "#include <new>")
    return "\n".join(lines)


def emit_kernel_cpp(ck: CollapsedKernel, name: str) -> str:
    """The double instantiation + C ABI wrapper + operand-name tables."""
    names = scal_order(ck)
    lines = [
        "/* generated by xckernel; do not edit. */",
        f'#include "xckernel/kernels/{name}.hpp"',
        "",
        'extern "C" {',
        "",
        f"const char* {name}_scal_names[{len(names)}] = {{",
    ]
    for n in names:
        lines.append(f'    "{n}",')
    lines += [
        "};",
        f"extern const int {name}_n_scal;",
        f"const int {name}_n_scal = {len(names)};",
        f"extern const int {name}_n_fields;",
        f"const int {name}_n_fields = "
        f"{len(names) - len(ck.libxc_args)};",
        "",
        "/* The C ABI keeps one homogeneous scal list (all double);",
        " * fields come first, functional-derivative arrays last, split at",
        f" * {name}_n_fields. */",
        f"int {name}(int64_t npts, int64_t nbf,",
        "           const double* chi, const double* dchi,",
        "           const double* lapl_chi, const double* hess_chi,",
        "           const double* const* scal, double* out) {",
        f"    return xckernel::{name}_t<double, double>(",
        "        npts, nbf, chi, dchi, lapl_chi, hess_chi,",
        f"        scal, scal + {len(names) - len(ck.libxc_args)}, out);",
        "}",
        "",
        "} // extern C",
        "",
    ]
    return "\n".join(lines)


# --- package emission (libxckernel) ------------------------------------------

_KERNEL_PROTO = ("int {name}(int64_t npts, int64_t nbf,\n"
                 "           const double* chi, const double* dchi,\n"
                 "           const double* lapl_chi, const double* hess_chi,\n"
                 "           const double* const* scal, double* out);")


def emit_header(kernel_names: List[str], version: str) -> str:
    """The public C header for libxckernel."""
    lines = [
        "/* libxckernel: generated exchange-correlation kernel contractions",
        " * (an automatic-differentiation backend for Libxc).",
        f" * Version {version}. Machine-generated by xckernel; do not edit.",
        " * Copyright (c) 2026 Susi Lehtola.",
        " *",
        " * ABI: one perturbation-batch entry per call; `scal` is an ordered",
        " * array of per-point scalar operands (see <name>_scal_names /",
        " * manifest.json); `out` is accumulated (+=). Returns 0 on success.",
        " * lapl_chi is the basis Laplacian collocation and hess_chi the",
        " * packed second-derivative collocation (6 blocks: xx,xy,xz,yy,",
        " * yz,zz); pass NULL when the kernel's family does not use them.",
        " * Kernels contain XC terms only: Coulomb, HF and range-separated",
        " * exchange are host-owned.",
        " *",
        " * Mixed functionals: libxckernel never evaluates functionals.",
        " * Every kernel is JOINTLY LINEAR in the functional-derivative",
        " * operands (each generated term carries exactly one derivative",
        " * factor; enforced at generation time), so hosts pass their own",
        " * coefficient-mixed (superfunctional) derivative arrays and",
        " * F[sum_i c_i f_i] = sum_i c_i F[f_i] holds exactly. Cross-family",
        " * mixtures: evaluate at the union family; absent derivatives are",
        " * zeros.",
        " */",
        "#ifndef XCKERNEL_H",
        "#define XCKERNEL_H",
        "#include <stdint.h>",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f'#define XCKERNEL_VERSION "{version}"',
        "",
    ]
    for name, order in kernel_names:
        if order == 0:
            lines.append(f"double {name}(int64_t npts, const double* w,")
            lines.append(f"              const double* rho, "
                         f"const double* zk);")
            lines.append("")
            continue
        lines.append(_KERNEL_PROTO.format(name=name))
        lines.append(f"extern const char* {name}_scal_names[];")
        lines.append(f"extern const int {name}_n_scal;")
        lines.append(f"extern const int {name}_n_fields;")
        lines.append("")
    lines += ["#ifdef __cplusplus", "}", "#endif", "#endif /* XCKERNEL_H */",
              ""]
    return "\n".join(lines)


def emit_f03(kernel_names: List[str], version: str) -> str:
    """The Fortran 2003 ISO_C_BINDING module (the xc_f03 idiom)."""
    lines = [
        "! libxckernel Fortran interface. Machine-generated by xckernel; do not edit.",
        "! Copyright (c) 2026 Susi Lehtola.",
        f"! Version {version}.",
        "! Scalar operands are passed as an array of C pointers in the order",
        "! given by the kernel's manifest entry (see manifest.json).",
        "module xckernel_f03",
        "  use, intrinsic :: iso_c_binding, only: c_int, c_int64_t, "
        "c_double, c_ptr",
        "  implicit none",
        "  public",
        "  interface",
    ]
    for name, order in kernel_names:
        if order == 0:
            lines += [
                f"    real(c_double) function {name}(npts, w, rho, zk) "
                f"bind(C, name='{name}')",
                "      import :: c_int64_t, c_double",
                "      integer(c_int64_t), value :: npts",
                "      real(c_double), intent(in) :: w(*), rho(*), zk(*)",
                f"    end function {name}",
            ]
            continue
        lines += [
            f"    integer(c_int) function {name}(npts, nbf, chi, dchi, "
            f"lapl_chi, hess_chi, scal, out) bind(C, name='{name}')",
            "      import :: c_int, c_int64_t, c_double, c_ptr",
            "      integer(c_int64_t), value :: npts, nbf",
            "      real(c_double), intent(in) :: chi(*), dchi(*)",
            "      type(c_ptr), value :: lapl_chi, hess_chi",
            "      type(c_ptr), intent(in) :: scal(*)",
            "      real(c_double), intent(inout) :: out(*)",
            f"    end function {name}",
        ]
    lines += ["  end interface", "end module xckernel_f03", ""]
    return "\n".join(lines)


def emit_cmake(kernel_names: List[Tuple[str, int]], version: str) -> str:
    import re as _re
    by_order: dict = {}
    for n, order in kernel_names:
        by_order.setdefault(order, []).append(n)
    groups = []
    for order in sorted(by_order):
        srcs = "\n        ".join(f"src/{n}.cpp" for n in by_order[order])
        groups.append(
            f"if(XCKERNEL_MAX_ORDER GREATER_EQUAL {order})\n"
            f"    target_sources(xckernel PRIVATE\n        {srcs}\n    )\n"
            f"endif()")
    grouped = "\n".join(groups)
    return f"""\
# libxckernel build. Machine-generated by xckernel; do not edit.
# Copyright (c) 2026 Susi Lehtola.
cmake_minimum_required(VERSION 3.16)
project(xckernel VERSION {version} LANGUAGES CXX)

option(XCKERNEL_FORTRAN "Build the Fortran interface module" ON)
# The response-kernel sources grow steeply with derivative order; exclude
# orders you do not need at configure time (kernels above the limit are
# declared in the header but not compiled).
set(XCKERNEL_MAX_ORDER 4 CACHE STRING
    "Highest derivative order to compile (0-4)")

add_library(xckernel)
{grouped}
target_compile_definitions(xckernel PUBLIC
    XCKERNEL_MAX_ORDER=${{XCKERNEL_MAX_ORDER}})
set_target_properties(xckernel PROPERTIES
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED ON
    POSITION_INDEPENDENT_CODE ON
    VERSION ${{PROJECT_VERSION}}
    SOVERSION ${{PROJECT_VERSION_MAJOR}})
target_include_directories(xckernel PUBLIC
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_SOURCE_DIR}}/include>
    $<INSTALL_INTERFACE:include>)

if(XCKERNEL_FORTRAN)
    enable_language(Fortran)
    add_library(xckernel_f03 fortran/xckernel_f03.f90)
    target_link_libraries(xckernel_f03 PUBLIC xckernel)
endif()

include(GNUInstallDirs)
install(TARGETS xckernel EXPORT xckernelTargets
    LIBRARY DESTINATION ${{CMAKE_INSTALL_LIBDIR}}
    ARCHIVE DESTINATION ${{CMAKE_INSTALL_LIBDIR}})
install(FILES include/xckernel.h DESTINATION ${{CMAKE_INSTALL_INCLUDEDIR}})
install(DIRECTORY include/xckernel DESTINATION ${{CMAKE_INSTALL_INCLUDEDIR}})
install(FILES manifest.json
    DESTINATION ${{CMAKE_INSTALL_DATADIR}}/xckernel)
if(XCKERNEL_FORTRAN)
    install(TARGETS xckernel_f03 EXPORT xckernelTargets
        LIBRARY DESTINATION ${{CMAKE_INSTALL_LIBDIR}}
        ARCHIVE DESTINATION ${{CMAKE_INSTALL_LIBDIR}})
endif()
install(EXPORT xckernelTargets NAMESPACE xckernel::
    DESTINATION ${{CMAKE_INSTALL_LIBDIR}}/cmake/xckernel)
"""


# --- order-0 (energy) kernels -------------------------------------------------

def emit_exc_hpp(name: str) -> str:
    return f"""/* machine-generated by xckernel; do not edit. Copyright (c) 2026 Susi Lehtola. */
#pragma once
#include <cstdint>
#include "xckernel/evaluator.hpp"

namespace xckernel {{

/* Exc = sum_g w_g rho_g zk_g (zk = Libxc energy density per particle).
 * T: host precision; Txc: the Libxc array type (double from Libxc). */
template <typename T, typename Txc = T>
XCK_HD inline T {name}_t(int64_t npts, const T* w, const T* rho,
                         const Txc* zk) {{
    T acc = T(0);
    for (int64_t g = 0; g < npts; ++g) acc += w[g] * rho[g] * T(zk[g]);
    return acc;
}}

}} // namespace xckernel
"""


def emit_exc_cpp(name: str) -> str:
    return f"""/* machine-generated by xckernel; do not edit. Copyright (c) 2026 Susi Lehtola. */
#include "xckernel/kernels/{name}.hpp"

extern "C" {{
double {name}(int64_t npts, const double* w, const double* rho,
              const double* zk) {{
    return xckernel::{name}_t<double, double>(npts, w, rho, zk);
}}
}} // extern C
"""
