"""GPAW writer: emit the fxc pair-coefficient channels as a standalone
machine-generated NumPy module for GPAW's Casida codes.

The emitted module provides, per functional family, a function

    fxc_pair_coefficients_<family>(ops) -> dict

taking a dict of NumPy arrays keyed by xckernel operand names (ground
fields rho / grad_rho_<xyz> / sigma / tau, Libxc derivative arrays
vrho ... v2tau2, and the pair fields rho_p1 / grad_rho_p1_<xyz> /
tau_p1) and returning the per-point coefficient fields {'rho': u,
'grad': v (3, ...), 'tau': w_tau}.  The host builds the analytic XC
pair potential as u - div(v) and contracts w_tau with the second
pair's kinetic-energy-density; everything is per grid point, so the
host's domain decomposition applies unchanged.

Reproduce with: python -m xckernel.emitters.gpawwriter --emit <file>
"""

from __future__ import annotations

from sympy.printing.numpy import NumPyPrinter

from ..engine.response import fxc_channels
from ..inputs.basis import AXES

FAMILIES = ("lda", "gga", "mgga_tau")

HEADER = '''\
"""fxc pair-coefficient channels for Casida-type XC couplings.

Machine-generated by xckernel (emitters.gpawwriter); do not edit.
Reproduce with: python -m xckernel.emitters.gpawwriter --emit <file>
Copyright (c) 2026 Susi Lehtola.

Each function takes a dict of NumPy arrays keyed by operand name and
returns {'rho': u, 'grad': [v_x, v_y, v_z], 'tau': w_tau (tau
families)}: per-point coefficient fields of the fxc contraction with
the pair fields labelled p1.  The analytic XC pair potential is
u - div(v); the tau channel is contracted with the second pair's
kinetic-energy-density.  Operand names follow xckernel/Libxc
conventions (rho, grad_rho_x, sigma, tau, vrho, vsigma, vtau,
v2rho2, v2rhosigma, v2sigma2, v2rhotau, v2sigmatau, v2tau2,
rho_p1, grad_rho_p1_x, tau_p1, ...).
"""
import numpy as np  # noqa: F401
'''


def _emit_function(family: str) -> str:
    printer = NumPyPrinter()
    ch = fxc_channels(family)
    names = sorted({s.name for e in ch.values() for s in e.free_symbols})
    L = [f"def fxc_pair_coefficients_{family}(ops):"]
    for n in names:
        L.append(f"    {n} = ops['{n}']")
    L.append(f"    u = {printer.doprint(ch['rho'])}")
    for ax in AXES:
        L.append(f"    v_{ax} = {printer.doprint(ch[f'grad_{ax}'])}")
    out = "{'rho': u, 'grad': [v_x, v_y, v_z]"
    if "tau" in ch:
        L.append(f"    w_tau = {printer.doprint(ch['tau'])}")
        out += ", 'tau': w_tau"
    L.append(f"    return {out}}}")
    return "\n".join(L)


def _emit_coefficient_function(family: str) -> str:
    from ..engine.response import fxc_coefficient_matrix
    printer = NumPyPrinter()
    m = fxc_coefficient_matrix(family)
    names = sorted({s.name for e in m.values() for s in e.free_symbols})
    L = [f"def fxc_coefficient_fields_{family}(ops):",
         '    """Symmetric per-point coefficient fields c[(a, b)] of the',
         "    semilocal fxc operator over the derivative slots",
         "    ('rho', 'x', 'y', 'z'[, 'tau']): the plane-wave kernel is",
         "    K_GG' = sum_ab fac_a(q+G)* FT[c_ab](G-G') fac_b(q+G')",
         '    with fac_rho = 1 and fac_i = 1j (q+G)_i."""']
    for n in names:
        L.append(f"    {n} = ops['{n}']")
    L.append("    c = {}")
    for (a, b), e in sorted(m.items()):
        L.append(f"    c[({a!r}, {b!r})] = {printer.doprint(e)}")
    L.append("    return c")
    return "\n".join(L)


def _emit_spin_function(family: str) -> str:
    from ..engine.spin_kernel import fxc_channels_spin
    printer = NumPyPrinter()
    ch = fxc_channels_spin(family)
    names = sorted({s.name for e in ch.values() for s in e.free_symbols})
    L = [f"def fxc_pair_coefficients_{family}_spin(ops):",
         '    """Spin-polarized per-point coefficient channels of the',
         "    fxc contraction with the pair fields labelled p1: keys",
         "    'rho_a'/'rho_b' (local), 'grad_a'/'grad_b' (vector), and",
         "    'tau_a'/'tau_b' (tau families).  Polarized Libxc arrays",
         '    carry their flat component packing (v2rho2_0..)."""']
    for n in names:
        L.append(f"    {n} = ops['{n}']")
    entries = []
    for s in ("a", "b"):
        L.append(f"    u_{s} = {printer.doprint(ch[f'rho_{s}'])}")
        entries.append(f"'rho_{s}': u_{s}")
        for ax in AXES:
            L.append(f"    v_{s}_{ax} = "
                     f"{printer.doprint(ch[f'grad_{s}_{ax}'])}")
        entries.append(f"'grad_{s}': [v_{s}_x, v_{s}_y, v_{s}_z]")
        if f"tau_{s}" in ch:
            L.append(f"    w_{s} = {printer.doprint(ch[f'tau_{s}'])}")
            entries.append(f"'tau_{s}': w_{s}")
    L.append("    return {" + ", ".join(entries) + "}")
    return "\n".join(L)


def _emit_triplet_function(family: str) -> str:
    from ..engine.spin_kernel import fxc_channels_st
    printer = NumPyPrinter()
    ch = fxc_channels_st(family, parity=-1)
    names = sorted({s.name for e in ch.values() for s in e.free_symbols})
    L = [f"def fxc_pair_coefficients_{family}_triplet(ops):",
         '    """Closed-shell TRIPLET (spin-flip) per-point coefficient',
         "    channels: the polarized Libxc arrays are evaluated at the",
         "    spin-compensated point (rho/2 per channel, flat packing",
         "    v2rho2_0..) and all fields/pair fields are ALPHA-channel",
         '    quantities (half the total pair density etc.)."""']
    for n in names:
        L.append(f"    {n} = ops['{n}']")
    L.append(f"    u = {printer.doprint(ch['rho'])}")
    for ax in AXES:
        L.append(f"    v_{ax} = {printer.doprint(ch[f'grad_{ax}'])}")
    out = "{'rho': u, 'grad': [v_x, v_y, v_z]"
    if "tau" in ch:
        L.append(f"    w_tau = {printer.doprint(ch['tau'])}")
        out += ", 'tau': w_tau"
    L.append(f"    return {out}}}")
    return "\n".join(L)


def emit_module() -> str:
    parts = [HEADER]
    parts.extend(_emit_function(f) for f in FAMILIES)
    parts.extend(_emit_coefficient_function(f) for f in FAMILIES)
    parts.extend(_emit_spin_function(f) for f in FAMILIES)
    parts.extend(_emit_triplet_function(f) for f in FAMILIES)
    return "\n\n".join(parts) + "\n"


if __name__ == "__main__":
    import sys
    if "--emit" in sys.argv:
        path = sys.argv[sys.argv.index("--emit") + 1]
        with open(path, "w") as f:
            f.write(emit_module())
        print(path)
    else:
        print(emit_module())
