"""GPAW writer: emit the fxc pair-coefficient channels as a standalone
machine-generated NumPy module for GPAW's Casida codes.

The emitted module provides, per functional family, a function

    fxc_pair_coefficients_<family>(ops) -> dict

taking a dict of NumPy arrays keyed by xckernel operand names (ground
fields rho / grad_rho_<xyz> / sigma / tau, Libxc derivative arrays
vrho ... v2tau2, and the pair fields rho_p1 / grad_rho_p1_<xyz> /
tau_p1) and returning the per-point coefficient fields {'rho': u,
'grad': v (3, ...), 'tau': w_tau}.  The host builds the analytic XC
pair potential as u - div(v) and contracts w_tau with the second
pair's kinetic-energy-density; everything is per grid point, so the
host's domain decomposition applies unchanged.

Reproduce with: python -m xckernel.emitters.gpawwriter --emit <file>
"""

from __future__ import annotations

from . import fieldkernel
from .fieldkernel import (ChannelLayout, FieldKernel, MappingLayout,
                          SpinChannelLayout)
from ..engine.response import fxc_channels
from ..inputs.basis import AXES

FAMILIES = ("lda", "gga", "mgga_tau")

HEADER = '''\
"""fxc pair-coefficient channels for Casida-type XC couplings.

Machine-generated by xckernel (emitters.gpawwriter); do not edit.
Reproduce with: python -m xckernel.emitters.gpawwriter --emit <file>
Copyright (c) 2026 Susi Lehtola.

Each function takes a dict of NumPy arrays keyed by operand name and
returns {'rho': u, 'grad': [v_x, v_y, v_z], 'tau': w_tau (tau
families)}: per-point coefficient fields of the fxc contraction with
the pair fields labelled p1.  The analytic XC pair potential is
u - div(v); the tau channel is contracted with the second pair's
kinetic-energy-density.  Operand names follow xckernel/Libxc
conventions (rho, grad_rho_x, sigma, tau, vrho, vsigma, vtau,
v2rho2, v2rhosigma, v2sigma2, v2rhotau, v2sigmatau, v2tau2,
rho_p1, grad_rho_p1_x, tau_p1, ...).
"""
import numpy as np  # noqa: F401
'''


def _channels(family: str) -> FieldKernel:
    """Pair-coefficient channels of the fxc contraction."""
    return FieldKernel(
        name=f"fxc_pair_coefficients_{family}",
        exprs=fxc_channels(family),
        layout=ChannelLayout(axes=AXES))


def _coefficient_fields(family: str) -> FieldKernel:
    """Symmetric coefficient matrix over the derivative slots."""
    from ..engine.response import fxc_coefficient_matrix
    return FieldKernel(
        name=f"fxc_coefficient_fields_{family}",
        exprs=fxc_coefficient_matrix(family),
        layout=MappingLayout(var="c"),
        doc=('    """Symmetric per-point coefficient fields c[(a, b)] of the',
             "    semilocal fxc operator over the derivative slots",
             "    ('rho', 'x', 'y', 'z'[, 'tau']): the plane-wave kernel is",
             "    K_GG' = sum_ab fac_a(q+G)* FT[c_ab](G-G') fac_b(q+G')",
             '    with fac_rho = 1 and fac_i = 1j (q+G)_i."""'))


def _spin_channels(family: str) -> FieldKernel:
    """Spin-polarized pair-coefficient channels."""
    from ..engine.spin_kernel import fxc_channels_spin
    return FieldKernel(
        name=f"fxc_pair_coefficients_{family}_spin",
        exprs=fxc_channels_spin(family),
        layout=SpinChannelLayout(axes=AXES),
        doc=('    """Spin-polarized per-point coefficient channels of the',
             "    fxc contraction with the pair fields labelled p1: keys",
             "    'rho_a'/'rho_b' (local), 'grad_a'/'grad_b' (vector), and",
             "    'tau_a'/'tau_b' (tau families).  Polarized Libxc arrays",
             '    carry their flat component packing (v2rho2_0..)."""'))


def _triplet_channels(family: str) -> FieldKernel:
    """Closed-shell triplet (spin-flip) pair-coefficient channels."""
    from ..engine.spin_kernel import fxc_channels_st
    return FieldKernel(
        name=f"fxc_pair_coefficients_{family}_triplet",
        exprs=fxc_channels_st(family, parity=-1),
        layout=ChannelLayout(axes=AXES),
        doc=('    """Closed-shell TRIPLET (spin-flip) per-point coefficient',
             "    channels: the polarized Libxc arrays are evaluated at the",
             "    spin-compensated point (rho/2 per channel, flat packing",
             "    v2rho2_0..) and all fields/pair fields are ALPHA-channel",
             '    quantities (half the total pair density etc.)."""'))


def _stress_fields(family: str) -> FieldKernel:
    """Per-point integrand of the explicit XC strain derivative."""
    from ..engine.strain import scale_operands, strain_energy_derivative
    comps = {}
    for a in range(3):
        for b in range(3):
            comps[(a, b)] = scale_operands(
                strain_energy_derivative(family, a, b),
                {"tau_tensor": 2.0})
    return FieldKernel(
        name=f"xc_stress_fields_{family}",
        exprs=comps,
        layout=MappingLayout(var="s"),
        doc=('    """Per-point integrand fields of the explicit XC strain',
             "    derivative dExc/deps_ab (the XC stress contribution",
             "    BEFORE symmetrization and 1/V): the host multiplies by",
             "    the quadrature weight and sums.  tau_tensor components",
             "    follow GPAW's convention (no 1/2; trace = 2 tau), and zk",
             '    is the per-particle Libxc energy density."""'))


#: every kernel the emitted module provides, in emission order
SPECS = (_channels, _coefficient_fields, _spin_channels, _triplet_channels,
         _stress_fields)


def emit_module(cse: bool = True) -> str:
    """The complete generated module.

    ``cse`` eliminates common subexpressions across the channels of each
    emitted function; it changes only the shape of the emitted code, not
    the values it computes.  On by default: the channels of one function
    share a great deal of structure (the pair fields and the Libxc
    derivative combinations recur across every component), so this cuts
    the emitted module by about a quarter and removes the corresponding
    repeated work at run time.  Pass ``cse=False`` to recover the
    literal one-expression-per-channel form, which is easier to read
    against the symbolic derivation."""
    parts = [HEADER]
    for spec in SPECS:
        parts.extend(fieldkernel.emit(spec(f), cse=cse) for f in FAMILIES)
    return "\n\n".join(parts) + "\n"


def main(argv=None):
    import argparse
    p = argparse.ArgumentParser(
        prog="python -m xckernel.emitters.gpawwriter",
        description=__doc__.splitlines()[0])
    p.add_argument("--emit", metavar="FILE",
                   help="write the module here instead of stdout")
    a = p.parse_args(argv)
    src = emit_module()
    if a.emit:
        with open(a.emit, "w") as f:
            f.write(src)
        print(a.emit)
    else:
        print(src)


if __name__ == "__main__":
    main()
