"""GPAW writer: emit the fxc pair-coefficient channels as a standalone
machine-generated NumPy module for GPAW's Casida codes.

The emitted module provides, per functional family, a function

    fxc_pair_coefficients_<family>(ops) -> dict

taking a dict of NumPy arrays keyed by xckernel operand names (ground
fields rho / grad_rho_<xyz> / sigma / tau, Libxc derivative arrays
vrho ... v2tau2, and the pair fields rho_p1 / grad_rho_p1_<xyz> /
tau_p1) and returning the per-point coefficient fields {'rho': u,
'grad': v (3, ...), 'tau': w_tau}.  The host builds the analytic XC
pair potential as u - div(v) and contracts w_tau with the second
pair's kinetic-energy-density; everything is per grid point, so the
host's domain decomposition applies unchanged.

Reproduce with: python -m xckernel.emitters.gpawwriter --emit <file>
"""

from __future__ import annotations

from sympy.printing.numpy import NumPyPrinter

from ..engine.response import fxc_channels
from ..inputs.basis import AXES

FAMILIES = ("lda", "gga", "mgga_tau")

HEADER = '''\
"""fxc pair-coefficient channels for Casida-type XC couplings.

Machine-generated by xckernel (emitters.gpawwriter); do not edit.
Reproduce with: python -m xckernel.emitters.gpawwriter --emit <file>
Copyright (c) 2026 Susi Lehtola.

Each function takes a dict of NumPy arrays keyed by operand name and
returns {'rho': u, 'grad': [v_x, v_y, v_z], 'tau': w_tau (tau
families)}: per-point coefficient fields of the fxc contraction with
the pair fields labelled p1.  The analytic XC pair potential is
u - div(v); the tau channel is contracted with the second pair's
kinetic-energy-density.  Operand names follow xckernel/Libxc
conventions (rho, grad_rho_x, sigma, tau, vrho, vsigma, vtau,
v2rho2, v2rhosigma, v2sigma2, v2rhotau, v2sigmatau, v2tau2,
rho_p1, grad_rho_p1_x, tau_p1, ...).
"""
import numpy as np  # noqa: F401
'''


def _emit_function(family: str) -> str:
    printer = NumPyPrinter()
    ch = fxc_channels(family)
    names = sorted({s.name for e in ch.values() for s in e.free_symbols})
    L = [f"def fxc_pair_coefficients_{family}(ops):"]
    for n in names:
        L.append(f"    {n} = ops['{n}']")
    L.append(f"    u = {printer.doprint(ch['rho'])}")
    for ax in AXES:
        L.append(f"    v_{ax} = {printer.doprint(ch[f'grad_{ax}'])}")
    out = "{'rho': u, 'grad': [v_x, v_y, v_z]"
    if "tau" in ch:
        L.append(f"    w_tau = {printer.doprint(ch['tau'])}")
        out += ", 'tau': w_tau"
    L.append(f"    return {out}}}")
    return "\n".join(L)


def emit_module() -> str:
    parts = [HEADER]
    parts.extend(_emit_function(f) for f in FAMILIES)
    return "\n\n".join(parts) + "\n"


if __name__ == "__main__":
    import sys
    if "--emit" in sys.argv:
        path = sys.argv[sys.argv.index("--emit") + 1]
        with open(path, "w") as f:
            f.write(emit_module())
        print(path)
    else:
        print(emit_module())
