"""NumPy emitter for the noncollinear (relativistic) response kernels.

Emits, per family, the machine-generated locally collinear potential and
fxc coefficient functions of :mod:`..engine.noncollinear`:

    nc_vxc_<family>(<fields>, <vrho_0 ...>, f_nabla)        -> (nV, ng)
    nc_fxc_<family>(<fields>, <first+second arrays>, f_nabla) -> (nV, nV, ng)

The fxc matrix contracts two perturbed noncollinear field sets as
``sum_ij d1[i] C[i, j] d2[j]`` per grid point -- the response kernel of
four-component (and two-component) TDDFT at the semilocal level.  Common
subexpressions are eliminated at emission.

CLI:  python -m xckernel.emitters.ncwriter --emit <file> [families...]
"""

from __future__ import annotations

from typing import List

import sympy as sp
from sympy.printing.numpy import NumPyPrinter

from ..engine.noncollinear import libxc_args, nc_fxc_matrix, nc_potential

_HEADER = '''"""Noncollinear (relativistic) xc potential and response kernels.

machine-generated by xckernel (ncwriter); do not edit.
Copyright (c) 2026 Susi Lehtola.
"""

import numpy

'''


def _emit_function(name: str, params: List[str], exprs, assigns: List[str],
                   alloc: str, ret: str) -> str:
    """One generated function: allocate, CSE the expressions, print the
    reductions, and assign each result to its target index expression."""
    p = NumPyPrinter()
    rep, red = sp.cse(exprs, optimizations="basic",
                      symbols=sp.numbered_symbols("t"))
    lines = [f"def {name}({', '.join(params)}):",
             "    ng = numpy.shape(rho_s)",
             f"    {alloc}"]
    lines += [f"    {s} = {p.doprint(e)}" for s, e in rep]
    for target, e in zip(assigns, red):
        if e == 0:
            continue
        lines.append(f"    {target} = {p.doprint(e)}")
    lines.append(f"    return {ret}")
    return "\n".join(lines) + "\n\n"


def emit(families=("lda", "gga")) -> str:
    """The complete generated module source."""
    src = _HEADER
    for family in families:
        fields, pot = nc_potential(family)
        fnames = [s.name for s in fields]
        n = len(fields)
        src += _emit_function(
            f"nc_vxc_{family}",
            fnames + libxc_args(family, 1) + ["f_nabla"],
            pot,
            [f"out[{i}]" for i in range(n)],
            f"out = numpy.zeros(({n},) + ng)",
            "out")
        fields2, C = nc_fxc_matrix(family)
        assert [s.name for s in fields2] == fnames
        exprs, assigns = [], []
        for i in range(n):
            for j in range(i, n):
                exprs.append(C[i][j])
                assigns.append(f"out[{i}, {i}]" if i == j else
                               f"out[{i}, {j}] = out[{j}, {i}]")
        src += _emit_function(
            f"nc_fxc_{family}",
            fnames + libxc_args(family, 2) + ["f_nabla"],
            exprs,
            assigns,
            f"out = numpy.zeros(({n}, {n}) + ng)",
            "out")
    return src


def main() -> None:
    import argparse
    ap = argparse.ArgumentParser(
        description="emit the noncollinear kernel module")
    ap.add_argument("--emit", required=True, help="output .py file")
    ap.add_argument("families", nargs="*", default=None)
    args = ap.parse_args()
    fams = tuple(args.families) if args.families else ("lda", "gga")
    with open(args.emit, "w") as f:
        f.write(emit(fams))
    print(f"wrote {args.emit} ({', '.join(fams)})")


if __name__ == "__main__":
    main()
