"""Emitters for the noncollinear (relativistic) response kernels.

Emits, per family, the machine-generated locally collinear potential and
fxc coefficient functions of :mod:`..engine.noncollinear`:

    nc_vxc_<family>(<fields>, <vrho_0 ...>, f_nabla)        -> (nV, ng)
    nc_fxc_<family>(<fields>, <first+second arrays>, f_nabla) -> (nV, nV, ng)

The fxc matrix contracts two perturbed noncollinear field sets as
``sum_ij d1[i] C[i, j] d2[j]`` per grid point -- the response kernel of
four-component (and two-component) TDDFT at the semilocal level.  Common
subexpressions are eliminated at emission.

Two backends:

``--lang numpy`` (default)
    A NumPy module; arrays in, arrays out.  Used by the validation suite.

``--lang c++``
    A self-contained header of per-grid-point ``inline`` functions in the
    idiom of grid-based host codes (GauXC and friends): scalars in,
    scalars out, no allocation, so the host owns the grid loop.  Besides
    the potential and the full kernel matrix it emits the CONTRACTION

        nc_fxc_contract_<family>(fields..., derivs..., f_nabla,
                                 trial fields..., out coefficients...)

    which is what a response solver actually wants: the kernel applied to
    one trial (transition) density, delivered as one coefficient per
    noncollinear field slot -- the same slots the potential occupies, so
    the host's existing Z-matrix assembly consumes it unchanged.

CLI:  python -m xckernel.emitters.ncwriter --emit <file> [--lang c++] [families...]
"""

from __future__ import annotations

from typing import List

import sympy as sp
from sympy.printing.c import C99CodePrinter
from sympy.printing.numpy import NumPyPrinter

from ..engine.noncollinear import (libxc_args, nc_fields, nc_fxc_matrix,
                                   nc_potential)

_HEADER = '''"""Noncollinear (relativistic) xc potential and response kernels.

machine-generated by xckernel (ncwriter); do not edit.
Copyright (c) 2026 Susi Lehtola.
"""

import numpy

'''


def _emit_function(name: str, params: List[str], exprs, assigns: List[str],
                   alloc: str, ret: str) -> str:
    """One generated function: allocate, CSE the expressions, print the
    reductions, and assign each result to its target index expression."""
    p = NumPyPrinter()
    rep, red = sp.cse(exprs, optimizations="basic",
                      symbols=sp.numbered_symbols("t"))
    lines = [f"def {name}({', '.join(params)}):",
             "    ng = numpy.shape(rho_s)",
             f"    {alloc}"]
    lines += [f"    {s} = {p.doprint(e)}" for s, e in rep]
    for target, e in zip(assigns, red):
        if e == 0:
            continue
        lines.append(f"    {target} = {p.doprint(e)}")
    lines.append(f"    return {ret}")
    return "\n".join(lines) + "\n\n"


def emit(families=("lda", "gga")) -> str:
    """The complete generated module source."""
    src = _HEADER
    for family in families:
        fields, pot = nc_potential(family)
        fnames = [s.name for s in fields]
        n = len(fields)
        src += _emit_function(
            f"nc_vxc_{family}",
            fnames + libxc_args(family, 1) + ["f_nabla"],
            pot,
            [f"out[{i}]" for i in range(n)],
            f"out = numpy.zeros(({n},) + ng)",
            "out")
        fields2, C = nc_fxc_matrix(family)
        assert [s.name for s in fields2] == fnames
        exprs, assigns = [], []
        for i in range(n):
            for j in range(i, n):
                exprs.append(C[i][j])
                assigns.append(f"out[{i}, {i}]" if i == j else
                               f"out[{i}, {j}] = out[{j}, {i}]")
        src += _emit_function(
            f"nc_fxc_{family}",
            fnames + libxc_args(family, 2) + ["f_nabla"],
            exprs,
            assigns,
            f"out = numpy.zeros(({n}, {n}) + ng)",
            "out")
    return src


# --------------------------------------------------------------------------
# C++ backend
# --------------------------------------------------------------------------

_CXX_HEADER = '''/**
 * Noncollinear (relativistic) exchange-correlation potential and response
 * kernels, for the locally collinear ansatz.
 *
 * MACHINE-GENERATED by xckernel (ncwriter); do not edit.
 * Copyright (c) 2026 Susi Lehtola.
 *
 * The functions are pure, per-grid-point and allocation-free: the caller
 * owns the grid loop.  Conventions, per grid point:
 *
 *   rho_s          charge density
 *   rho_{x,y,z}    magnetization vector m
 *   grad_rho_s_{x,y,z}, grad_rho_{x,y,z}_{x,y,z}   their Cartesian gradients
 *   f_nabla        sgn( grad rho_s . sum_J rho_J grad rho_J ), +-1
 *
 * The collinear variables handed to the functional library are
 *
 *   n_{+,-}  = ( rho_s +- |m| ) / 2
 *   gamma^{++,--} = ( |grad rho_s|^2 + sum_J |grad rho_J|^2 ) / 4
 *                   +- f_nabla sqrt( sum_J (grad rho_s . grad rho_J)^2 ) / 2
 *   gamma^{+-}    = ( |grad rho_s|^2 - sum_J |grad rho_J|^2 ) / 4
 *
 * and the derivative arguments (vrho_0, ..., v2sigma2_5) follow the
 * standard spin-polarized Libxc packing, so they can be passed straight
 * through from a polarized functional evaluation.
 *
 * NOTE the |m| -> 0 limit: the map is only piecewise smooth there and the
 * transverse kernel components carry 1/|m|.  Hosts must apply their usual
 * small-|m| regularization (a magnetization cutoff) before calling.
 */

#pragma once

#include <cmath>

namespace xckernel {

'''


def _cxx_function(name: str, params: List[str], exprs, out_names: List[str],
                  doc: str) -> str:
    """One generated C++ function: scalar in, scalar out (by reference)."""
    p = C99CodePrinter()
    rep, red = sp.cse(exprs, optimizations="basic",
                      symbols=sp.numbered_symbols("t"))
    # A parameter can be absent from the reduced expressions (the LDA
    # potential, e.g., is independent of rho_s and of the sign factor);
    # keep it in the signature for uniformity but mark it maybe_unused.
    used = set()
    for e in list(red) + [e for _s, e in rep]:
        used |= {s.name for s in e.free_symbols}
    sig = ", ".join(("double " if q in used else "[[maybe_unused]] double ")
                    + q for q in params)
    sig += ", " + ", ".join(f"double& {q}" for q in out_names)
    lines = [f"/** {doc} */",
             f"inline void {name}( {sig} ) {{"]
    lines += [f"  const double {s} = {p.doprint(e)};" for s, e in rep]
    for target, e in zip(out_names, red):
        lines.append(f"  {target} = {p.doprint(e)};")
    lines.append("}")
    return "\n".join(lines) + "\n\n"


def emit_cxx(families=("lda", "gga")) -> str:
    """The complete generated C++ header."""
    src = _CXX_HEADER
    for family in families:
        fields, pot = nc_potential(family)
        fnames = [s.name for s in fields]
        n = len(fields)
        d1 = [sp.Symbol(f"t{q}") for q in fnames]     # trial density fields

        # potential: dE/dV_i
        src += _cxx_function(
            f"nc_vxc_{family}",
            fnames + libxc_args(family, 1) + ["f_nabla"],
            pot, [f"v_{q}" for q in fnames],
            f"Noncollinear {family.upper()} exchange-correlation potential: "
            f"the derivative of the energy density with respect to each "
            f"noncollinear field, v_X = dE/dX.")

        fields2, C = nc_fxc_matrix(family)
        assert [s.name for s in fields2] == fnames

        # contraction with one trial density: sum_j C_ij d_j
        contracted = [sp.Add(*[C[i][j] * d1[j] for j in range(n)])
                      for i in range(n)]
        src += _cxx_function(
            f"nc_fxc_contract_{family}",
            fnames + libxc_args(family, 2) + ["f_nabla"]
            + [s.name for s in d1],
            contracted, [f"k_{q}" for q in fnames],
            f"Noncollinear {family.upper()} exchange-correlation kernel "
            f"applied to one trial density: k_X = sum_Y f_xc[X,Y] tY, "
            f"delivered in the same field slots as the potential.")

        # the full symmetric matrix, for hosts that want it explicitly
        upper = [(i, j) for i in range(n) for j in range(i, n)]
        src += _cxx_function(
            f"nc_fxc_matrix_{family}",
            fnames + libxc_args(family, 2) + ["f_nabla"],
            [C[i][j] for i, j in upper],
            [f"c_{fnames[i]}_{fnames[j]}" for i, j in upper],
            f"Noncollinear {family.upper()} exchange-correlation kernel "
            f"matrix f_xc[X,Y] over the noncollinear field slots; upper "
            f"triangle, symmetric.")
    return src + "}  // namespace xckernel\n"


def main() -> None:
    import argparse
    ap = argparse.ArgumentParser(
        description="emit the noncollinear kernel module")
    ap.add_argument("--emit", required=True, help="output file")
    ap.add_argument("--lang", choices=("numpy", "c++"), default="numpy")
    ap.add_argument("families", nargs="*", default=None)
    args = ap.parse_args()
    fams = tuple(args.families) if args.families else ("lda", "gga")
    src = emit(fams) if args.lang == "numpy" else emit_cxx(fams)
    with open(args.emit, "w") as f:
        f.write(src)
    print(f"wrote {args.emit} ({args.lang}; {', '.join(fams)})")


if __name__ == "__main__":
    main()
