"""VeloxChem writer plugin: regenerate DensityGridQuad mode branches.

VeloxChem organizes quadratic (and cubic) response as a generic
derivative-array contraction (XCIntegratorFor*.cpp) fed by mode-specific
pointwise products of perturbed densities (DensityGridQuad.cpp,
DensityGridCubic.cpp).  The product code is fully determined by a small
pairing table: which pairs of first-order densities multiply into which
output slot, with what prefactor, and whether the densities are complex.
The hand-written files expand this table times the product template times
the real/imaginary decomposition, which is what makes them tens of
thousands of lines long.

This module emits those branches from the pairing table.  The product
template per family is fixed by VeloxChem's generic contraction stage:

    gam    +=     rho_A rho_B            (both orderings)
    gamK   += 2 * dK rho_A rho_B         (both orderings, K in xyz)
    gamKL  +=     dK rho_A dL rho_B      (both orderings)

complex products expand through VeloxChem's prod2_r/prod2_i helpers.
The pairing tables below follow the density layout documented in each
python response driver's get_densities().
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

AXES = ("x", "y", "z")


@dataclass(frozen=True)
class PairSpec:
    """One output slot of a quadratic-response product branch.

    out:    output slot index (per repetition block)
    a, b:   first-order density labels (indices into the block's densities)
    factor: overall prefactor in front of the symmetrized product
    """
    out: int
    a: str
    b: str
    factor: float = 1.0


@dataclass(frozen=True)
class ModeSpec:
    """Pairing table of a quadratic-response mode.

    densities: complex first-order densities per block, in storage order;
               each occupies two real slots (Re, Im) of the density grid.
    outputs:   complex output slots per block; each occupies two real gam
               slots (Re, Im).
    pairs:     the products.
    """
    name: str
    densities: Tuple[str, ...]
    n_out: int
    pairs: Tuple[PairSpec, ...]


#: Density layouts follow get_densities() in the python response drivers.
MODES = {
    # quadraticresponsedriver.get_densities: Db, Dc; one output Fbc
    "QRF": ModeSpec(name="QRF", densities=("B", "C"), n_out=1,
                    pairs=(PairSpec(0, "B", "C"),)),
}


def _gam_decl(n_out: int, gga: bool, ind: str) -> List[str]:
    lines = []
    for slot in range(n_out):
        pos = f"{2 * n_out} * j + {2 * slot}" if n_out > 1 \
            else f"2 * j"
        pos_i = f"{2 * n_out} * j + {2 * slot + 1}" if n_out > 1 \
            else f"2 * j + 1"
        lines.append(f"{ind}auto gam{slot}_r = gam({pos});")
        lines.append(f"{ind}auto gam{slot}_i = gam({pos_i});")
        if gga:
            for ax in AXES:
                lines.append(f"{ind}auto gam{slot}_{ax}_r = "
                             f"gam{ax.upper()}({pos});")
                lines.append(f"{ind}auto gam{slot}_{ax}_i = "
                             f"gam{ax.upper()}({pos_i});")
            for a1 in AXES:
                for a2 in AXES:
                    lines.append(f"{ind}auto gam{slot}_{a1}{a2}_r = "
                                 f"gam{a1.upper()}{a2.upper()}({pos});")
                    lines.append(f"{ind}auto gam{slot}_{a1}{a2}_i = "
                                 f"gam{a1.upper()}{a2.upper()}({pos_i});")
    return lines


def _prod(part: str, fa: str, fb: str) -> str:
    """prod2_{part} of two complex fields given by their stem names."""
    return (f"prod2_{part}({fa}_r[i],{fa}_i[i],{fb}_r[i],{fb}_i[i])")


def _fmt_factor(x: float) -> str:
    return f"{x:.1f} * " if x != 1.0 else ""


def _accum(target: str, factor: float, part: str,
           fa1: str, fb1: str, fa2: str, fb2: str, ind: str) -> List[str]:
    """target += factor * (prod(a1,b1) + prod(a2,b2)); both orderings."""
    f = _fmt_factor(factor)
    return [f"{ind}{target}[i] += {f}{_prod(part, fa1, fb1)}",
            f"{ind}            + {f}{_prod(part, fa2, fb2)};"]


def emit_branch(mode: str, family: str, indent: int = 8) -> str:
    """The full quadMode branch body for DensityProdFor{LDA,GGA}."""
    spec = MODES[mode.upper()]
    gga = {"lda": False, "gga": True}[family]
    ind0 = " " * indent
    ind1 = ind0 + " " * 4
    ind2 = ind1 + " " * 4
    ind3 = ind2 + " " * 4

    nden = 2 * len(spec.densities)   # real slots per block
    lines = [f"{ind0}// generated by xckernel vlxwriter: mode {spec.name}, "
             f"family {family.upper()}",
             f"{ind0}for (int j = 0; j < numdens / {2 * spec.n_out}; j++)",
             ind0 + "{"]
    for k, lbl in enumerate(spec.densities):
        for part, off in (("r", 0), ("i", 1)):
            lines.append(f"{ind1}auto rho{lbl}_{part} = "
                         f"rwDensityGrid.alphaDensity"
                         f"({nden} * j + {2 * k + off});")
            if gga:
                for ax in AXES:
                    lines.append(f"{ind1}auto grad{lbl}_{ax}_{part} = "
                                 f"rwDensityGrid.alphaDensityGradient"
                                 f"{ax.upper()}({nden} * j + {2 * k + off});")
        lines.append("")
    lines += _gam_decl(spec.n_out, gga, ind1)
    lines.append("")
    lines.append(f"{ind1}for (int i = 0; i < npoints; i++)")
    lines.append(ind1 + "{")
    for p in spec.pairs:
        A, B, s = p.a, p.b, p.out
        for part in ("r", "i"):
            lines += _accum(f"gam{s}_{part}", p.factor, part,
                            f"rho{A}", f"rho{B}",
                            f"rho{B}", f"rho{A}", ind2)
        if not gga:
            continue
        for ax in AXES:
            for part in ("r", "i"):
                lines += _accum(f"gam{s}_{ax}_{part}", 2.0 * p.factor, part,
                                f"grad{A}_{ax}", f"rho{B}",
                                f"grad{B}_{ax}", f"rho{A}", ind2)
        for a1 in AXES:
            for a2 in AXES:
                for part in ("r", "i"):
                    lines += _accum(f"gam{s}_{a1}{a2}_{part}", p.factor, part,
                                    f"grad{A}_{a1}", f"grad{B}_{a2}",
                                    f"grad{B}_{a1}", f"grad{A}_{a2}", ind2)
    lines.append(ind1 + "}")
    lines.append(ind0 + "}")
    return "\n".join(lines)


def main() -> None:
    import sys
    mode = sys.argv[1] if len(sys.argv) > 1 else "QRF"
    family = sys.argv[2] if len(sys.argv) > 2 else "gga"
    print(emit_branch(mode, family))


if __name__ == "__main__":
    main()
